version: "3.8"

services:
  static-files:
    build:
      context: ./static/
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    labels:
      - traefik.enable=true
      - traefik.http.routers.attendance.entrypoints=websecure
      - traefik.http.routers.attendance.rule=Host(`attendance.christianfds.dev`)
      - traefik.http.routers.attendance.tls.certresolver=letsencryptresolver
      - traefik.http.services.static-files.loadbalancer.server.port=6000
    ports:
      - 6000:6000
    networks:
      - traefik

networks:
  traefik:
    external: true
